# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push but only for the "main" branch
  push:
    branches: [ "main", "develop", "feature/*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    concurrency: build-${{ github.ref }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Update PATH for npm
        run: echo "$(npm bin)" >> $GITHUB_PATH
      - name: build
        uses: SAP/project-piper-action@master
        with:
          command: mtaBuild
      - run: npm pack
      - name: Upload mtar
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: mtar
          path: ./*.mtar
      - name: Upload npm package
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: npm
          path: ./*.tgz
  deploy:
    needs: build
    runs-on: ubuntu-latest
    concurrency: deploy-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: Download mtar
        uses: actions/download-artifact@v3
        with:
          name: mtar
      - name: Download npm package
        uses: actions/download-artifact@v3
        with:
          name: npm
      - run: pwd
      - run: ls
      - name: cloudFoundryDeploy
        uses: SAP/project-piper-action@master
        with:
          command: cloudFoundryDeploy
        env:
          PIPER_username: ${{ secrets.CF_USERNAME }}
          PIPER_password: ${{ secrets.CF_PASSWORD }}
#      - name: nexusUpload
#        uses: SAP/project-piper-action@master
#        with:
#          command: nexusUpload
