# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push but only for the "main" branch
  push:
    branches: [ "main", "feature/gh_action" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    concurrency: build-${{ github.ref }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: help
        uses: SAP/project-piper-action@master
        with:
          command: help
      - name: mtaBuild
        uses: SAP/project-piper-action@master
        with:
          command: mtaBuild
          flags: --noTelemetry
  deploy:
    needs: build
    runs-on: ubuntu-latest
    concurrency: deploy-${{ github.ref }}
  
