# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push but only for the "main" branch
  push:
    branches: [ "main", "develop" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    concurrency: build-${{ github.ref }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build:cf
  deploy:
    needs: build
    runs-on: ubuntu-latest
    concurrency: deploy-${{ github.ref }}
    steps:
      - name: cloudFoundryDeploy
        uses: SAP/project-piper-action@master
        with:
          command: cloudFoundryDeploy
      - name: nexusUpload
        uses: SAP/project-piper-action@master
        with:
          command: nexusUpload
