# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push but only for the "main" branch
  push:
    branches: [ "main", "develop", "feature/*" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    concurrency: build-${{ github.ref }}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Update PATH for npm
        run: echo "$(npm bin)" >> $GITHUB_PATH
      - name: build
        uses: SAP/project-piper-action@master
        with:
          command: mtaBuild
      - run: npm pack
      - name: Upload mtar
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: mtar
          path: ./*.mtar
      - name: Upload npm package
        uses: actions/upload-artifact@v3
        if: success()
        with:
          name: npm
          path: ./*.tgz
  deploy:
    needs: build
    runs-on: ubuntu-latest
    concurrency: deploy-${{ github.ref }}
    steps:
      - name: Install cf CLI
        run: |
          wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
          echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
          sudo apt-get update
          sudo apt-get install cf8-cli
          cf add-plugin-repo CF-Community https://plugins.cloudfoundry.org
          cf install-plugin -r CF-Community multiapps -f
          cf plugins
      - uses: actions/checkout@v3
      - name: Download mtar
        uses: actions/download-artifact@v3
        with:
          name: mtar
      - name: Download npm package
        uses: actions/download-artifact@v3
        with:
          name: npm
      - name: Install JFrog CLI
        uses: jfrog/setup-jfrog-cli@v2
        with:
          version: latest
        env:
          JF_URL: ${{ secrets.ARTIFACTORY_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.ARTIFACTORY_ACCESS_TOKEN }}
      - name: Deploy npm package
        run: |
          jf rt ping
          jf rt upload "*.tgz" generic-sap-cc
      - name: cloudFoundryDeploy
        uses: SAP/project-piper-action@master
        with:
          command: cloudFoundryDeploy
        env:
          PIPER_username: ${{ secrets.CF_USERNAME }}
          PIPER_password: ${{ secrets.CF_PASSWORD }}
#      - name: nexusUpload
#        uses: SAP/project-piper-action@master
#        with:
#          command: nexusUpload
